### ISSUE TITLE
[Question] Is it safe to override `emit`?

### ISSUE THREAD

**Issue by kevcao-certik** [sindresorhus/emittery#108]
For my usecase, I wanted to add an environment variable that will intercept event emission if it set. I wrote a wrapper class around emittery that simply avoids calling the super `emit` function if the environment variable is set. However, I noticed additional events being emitted such as `listenerAdded`, which in my class would be intercepted and not emitted. Will this cause any issues?

**Comment by sindresorhus** [comment]
Subclassing and changing the behavior of an external class is generally not supported and done on your own risk. It should work fine right now, but I cannot guarantee it will forever keep working.
