### ISSUE TITLE
return listeners' results in emit()

### ISSUE THREAD

**Issue by kor3k** [sindresorhus/emittery#119]
please, can you return the result of the listeners in `emit()` & `emitSerial()`?

like:
https://github.com/sindresorhus/emittery/blob/main/index.js#L364

```js
return await Promise.all([ ...
```

and 

```js
await resolvedPromise;
const results = []

/* eslint-disable no-await-in-loop */
for (const listener of staticListeners) {
	if (listeners.has(listener)) {
		results.push(await listener(eventData));
	}
}

for (const listener of staticAnyListeners) {
	if (anyListeners.has(listener)) {
		results.push(await listener(eventName, eventData));
	}
}
/* eslint-enable no-await-in-loop */

return Promise.resolve(results)
```

**Comment by sindresorhus** [comment]
No. That's out of scope for an events system. You want some kind of IPC system.

**Comment by kor3k** [comment]
well, this similar lib does exactly that
https://github.com/EventEmitter2/EventEmitter2?tab=readme-ov-file#emitteremitasyncevent--eventns-arg1-arg2-

i am looking for a replacement as it has bugs and seems pretty much dead.  but ok.
