### ISSUE TITLE
Type-check event names?

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#12]
Despite the intent communicated in the documentation and tests, Emittery's use of `Map` means event names can be any kind of JavaScript value — not just strings.

I think we should limit this to strings, though it might be nice to also support symbols. That said any TypeScript / Flow interfaces will be easier to use if we only support strings.

**Comment by novemberborn** [comment]
This will need to be resolved for #1.

**Comment by sindresorhus** [comment]
We should enforce only strings.

**Comment by dinoboff** [comment]
Why not support Symbol? For #1, it just needs to support event key as an array. Even if the list of event key is provided as a string (e.g.: `on('start:*')` or `on('start:foo start:bar')`), it's just a matter of filtering symbol event keys.

**Comment by sindresorhus** [comment]
Why do you want support for Symbols? How would you use it?

**Comment by dinoboff** [comment]
To avoid name collision if you expect an emitter class to be extended and for event you don't especially need to expose.

For those cases, you can add namespace to the event name, or not expose the emitter, but if it doesn't complicate `emittery`internals, supporting `Symbol` like EventEmitter would be useful.

**Comment by sindresorhus** [comment]
@dinoboff That's a good use-case. I hadn't thought of that.
