### ISSUE TITLE
Add TypeScript definition

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#13]
It'd be great to have a TypeScript definition. Note that there should be a build step to duplicate the definition for the `emittery/legacy` module.

**Comment by novemberborn** [comment]
We should resolve #12 first, since it's no fun to type the event name as `any`.

**Comment by dinoboff** [comment]
Is it possible to define it in such a way to you can provide the event key types, e.g.:
```ts
type EventType = 'value' | 'end' | 'error';

const ev: Emittery<EventType> = new Emittery();

ev.on('finish'); // Compile error
```

**Comment by sindresorhus** [comment]
@dinoboff Yeah, that should be possible and would be very useful. Could take it further and also make the emitted value be type-safe:

```typescript
import Emittery from 'emittery';

type EventType = {
	value: string
	end: undefined
	error: Error
};

const emitter = new Emittery<EventType>();
```

**Comment by dinoboff** [comment]
That PR doesn't allow doesn’t allow to map the type of the event data to each event name (other than by overloading the `on` and `emit` method for each event name) but it's start.
