### ISSUE TITLE
emittery/legacy is not created when installing from GitHub

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#15]
Apologies, I still haven't figured out how to do this. We should build `legacy.js` when installing a clone from GitHub, during CI, before publishing, *and* when using npm to install from GitHub. The latter isn't working now.

```console
$ npm i https://github.com/sindresorhus/emittery
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tmp.c6sykcipWf@1.0.0 No description
npm WARN tmp.c6sykcipWf@1.0.0 No repository field.

+ emittery@0.2.0
added 1 package in 4.043s
```

```console
$ ls node_modules/emittery
index.js  license  package.json  readme.md
```

**Comment by sindresorhus** [comment]
Why complicate things? The official way is to install it through npm.

**Comment by novemberborn** [comment]
It's useful to access prerelease features or to install an in-progress branch without linking, so that it can run in CI.

**Comment by sindresorhus** [comment]
Sure, but for tiny modules like this one, features are usually released soon after being merged. But if you need this, feel free to do it. I'm just trying to keep the boilerplate down.

**Comment by darkobits** [comment]
NPM (at least `5.x`) will run a package's `prepare` script when installing Git refs, so this should be doable in 1LOC.

```json
"prepare": "npm run build"
```

**Comment by novemberborn** [comment]
Indeed, thanks @darkobits!
