### ISSUE TITLE
Support Symbol as `eventName`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/emittery#16]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/emittery/issues/16)

See https://github.com/sindresorhus/emittery/issues/12#issuecomment-348813948 for use-case.

I think #13 should be implemented first though, so we can make sure it's not hard to define in a TS type definition.

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#43 Allow symbol event names](https://issuehunt.io/r/sindresorhus/emittery/pull/43)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/emittery/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by novemberborn** [comment]
We'll be able to support this in the `Emittery` class itself, but TypeScript cannot yet express symbol types sufficiently for use in the `Emittery.Typed` class. That's OK though, we can definitely tackle this now.

**Comment by sindresorhus** [comment]
TypeScript 2.7 is now out with support for `Symbol`: https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#unique-symbol-types-and-const-named-properties

**Comment by dinoboff** [comment]
AFAIK, the support is still limited: they cannot be use with `keyOf` or as index signature parameter. It can be used in overloaded method signatures however.

**Comment by sindresorhus** [comment]
Relevant TypeScript issues:

- https://github.com/Microsoft/TypeScript/issues/20721
- https://github.com/Microsoft/TypeScript/issues/21983

**Comment by sindresorhus** [comment]
The above issues has been fixed.
