### ISSUE TITLE
Revisit off() and offAny() without listener

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#22]
It seems to me the current behavior of `off()` and `offAny()` is a bit of a footgun:

```js
emitter.off('event', myAccidentallyUndefinedListener)
```

This ends up unsubscribing *all* listeners for `event`.

If you view emitters as producers, what is the use case for one event consumer to modify the subscriptions of another? Is this more a feature for the code that created the emitter, and if so perhaps this could be replaced by a generic `emitter.dispose()` function which unsubscribes *all* listeners, and prevents new subscriptions?

**Comment by sindresorhus** [comment]
Yeah, I regret adding that. I was very back-and-forth about adding it initially, but I ended up doing it.

**Comment by sindresorhus** [comment]
> Is this more a feature for the code that created the emitter, and if so perhaps this could be replaced by a generic emitter.dispose() function which unsubscribes all listeners, and prevents new subscriptions?

Yes, I think that would be much better.

**Comment by novemberborn** [comment]
The producer / consumer distinction does somewhat fall apart because it's all on the same object. I think that's fine, though we could investigate a helper method which returns bound subscription methods that can be mixed into a public object… anyway let's see how Emittery gets used first.

Is `dispose()` too generic or imposing when `Emittery` is subclassed though?

Should `on()` and `emit()` throw after `dispose()`, or just be no-ops?

**Comment by sindresorhus** [comment]
Can this be closed now that https://github.com/sindresorhus/emittery/pull/25 is merged?
