### ISSUE TITLE
Obfuscate internal _events and _anyEvents fields?

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#23]
`_events` and `_anyEvents` could potentially conflict when `Emittery` is subclassed. We could hide them in a `WeakMap` or otherwise namespace the fields so collisions are less likely.

If we don't go the `WeakMap` route we should add them as `private` fields in the TypeScript definition.

@sindresorhus what's your preference?

**Comment by sindresorhus** [comment]
Yes, WeakMap is a good solution.

**Comment by dinoboff** [comment]
Or use symbols.

ps: `_getListeners` should be in the type definition too.

**Comment by sindresorhus** [comment]
WeakMaps are better: http://2ality.com/2016/01/private-data-classes.html

**Comment by sindresorhus** [comment]
> ps: _getListeners should be in the type definition too.

Why? It's a private method. Users couldn't have access to the other listeners.

**Comment by dinoboff** [comment]
I think you should include private* methods and properties so that TS can emit an error when they get used or overridden.

* TS's private, I don't know what will happen once TS implement ES private properties.

**Comment by novemberborn** [comment]
PR at #24, which also removes the need for `_getListeners()`.
