### ISSUE TITLE
Async iterator support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/emittery#3]
Could be a nicer way to handle multiple events:

```js
for await (const data of emitter.on('🦄')) {
     console.log(data);
}
```

Spec: https://github.com/tc39/proposal-async-iteration

**Comment by bvx89** [comment]
Maybe I don't understand this correctly, but how would one unsubscribe from these events?

**Comment by dinoboff** [comment]
By breaking out of the loop.

But I don't think it's a good fit. Emitter push data, while you pull data from an iterator. To work the emitter would have to either queue events or to skip events emitted while the async loop block is getting processed.

**Comment by sindresorhus** [comment]
@dinoboff It would queue events. That's how Emittery works already though, as events are emitted async, so they're placed on the event loop (queue). It's probably not useful for the common case, true, but sometimes I just want to gather a certain amount of events from an emitter or all, and then iterating like this would be a nice way of handling it.

**Comment by novemberborn** [comment]
[Weak references](https://github.com/tc39/proposal-weakrefs) would allow the iterator to be garbage collected, and thus the queue as well. Support for that is probably still a long way off though.

**Comment by dinoboff** [comment]
@sindresorhus they are queued to some extends but the queue get flushed on the next tick whether the consumer is ready or not.

**Comment by dinoboff** [comment]
@bvx89 It would be something like that

```js
function iterator(emitter, eventName) {
  return {
    async *[Symbol.asyncIterator]() {
      const queue = [];
      const off = emitter.on(eventName, (data: any) => queue.push(data));

      try {
        while (true) {
          if (queue.length == 0) {
            await emitter.once(eventName);
          }

          yield queue.splice(0, 1);
        }
      } finally {
        // Called once the iterator result `return` or `throw` methods are called;
        // e.g. if the loop block `break` or `throw`.
        off();
      }
    }
  }
}
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/emittery/pull/40
