### ISSUE TITLE
Support listening for listener changes

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/emittery#46]
EventEmitter's implementation:

```js
const EventEmitter = require("events")

const emitter = new EventEmitter()

emitter.on("newListener", (data, callback) => {

})

emitter.on("removeListener", (data, callback) => {

})
```

cc @sindresorhus

**Comment by sindresorhus** [comment]
Do you have an actual need for this? If so, could you elaborate? I've intentionally not implemented a lot of the `EventEmitter` interface as I think it's way too bloated and it has a lot of bad choices.

**Comment by Richienb** [comment]
@sindresorhus This feature can be used to detect if a listener has been added so that background logic isn't run if there aren't any listeners to receive it.

Alternatively, this could also be used to keep track of all added listeners as soon as they are added to run some sort of refresh.

**Comment by sindresorhus** [comment]
Alright, but do *you* actually need this?

**Comment by Richienb** [comment]
@sindresorhus Yup! I'm migrating my code from `EventEmitter` to `emittery` and this is the only roadblock.

Here's the code I'm trying to migrate: https://github.com/Richienb/xoi/blob/master/src/index.ts#L154-L169

**Comment by sindresorhus** [comment]
Ok. I don't really like how `EventEmitter` exposes this as just a normal event name. I think we should wait for https://github.com/sindresorhus/emittery/pull/43 and do the events as a Symbol instead:

```js
emitter.on(Emittery.newListener, data => { … });
```

**Comment by Richienb** [comment]
@sindresorhus What's blocking #43 from merging?

**Comment by sindresorhus** [comment]
It's in the comments:

> Lemme know if we want this temporal type relaxation or if we will wait for the typescript patch to land so I could update docs accordingly.

> Don't forget to update the docs.

**Comment by sindresorhus** [comment]
If you cannot wait, I suggest implementing this with just string event names, do a PR here, and use your fork in the meantime.

**Comment by stroncium** [comment]
We need a decision on if we count this new events as events for the purpose of `onAny`/`offAny`.

Also, since we're not going with strings but symbols, we're not directly compatible with `EventEmitter` in this respect so we have a chance to think about how we name the symbols.
I don't really like `newListener`/`removeListener`, as they don't convey temporal relation to the event  in question and are relating to different classes of events("new" vs "remove"). Maybe `listenerAdded`/`listenerRemoved` instead (going off *after* event happened as the name suggests)?

**Comment by Richienb** [comment]
The only solution I see is to have `onAny` and `offAny` trigger separate events.

Emittery would then export these symbols:

- `listenerAdded`
- `listenerRemoved`
- `anyListenerAdded`
- `anyListenerRemoved`

**Comment by sindresorhus** [comment]
I like `listenerAdded`.

**Comment by sindresorhus** [comment]
For `onAny`, do we really need a separate symbol? `onAny` could accept `.listenerAdded` too.

**Comment by stroncium** [comment]
@sindresorhus It's the opposite that is not so obvious. Probably easier to say it in code:
```js
let ee = new Emittery();
let onListenerAdded = ([eventName, listener]) => {
  // note we have to pass array as arguments, otherwise we will not match listener signature
};

ee.on(Emittery.listenerAdded, onListenerAdded);
// will onListenerAdded([Emittery.listenerAdded, onListenerAdded]) get called after that?
// (we are supposed to emit event after listener was added)
// if we don't want that we have named our `listenerAdded` incorrectly

ee.onAny((eventName, data) => {
});
// will onListenerAdded get called after that, if so with what arguments?
```

Changing `any` to symbol seems to solve part of the question, though as I stated in #43 comments I don't like this approach personally.

Ordering of events is still a question though.

Also, looking at all that I wondered, isn't ability to just override `on`/`off` and handle it the way you want while calling super methods? After all we are living in era when JS got classes and standard method to operate on them.

**Comment by Richienb** [comment]
@sindresorhus 

> `onAny` could accept `.listenerAdded` too.

In that case, when would `listenerAdded` be called for `onAny`? We can't just loop through all the current listeners since that simply *won't work* as referred to in https://github.com/sindresorhus/emittery/issues/46#issuecomment-586632410.

Using separate events for `anyOn` and `anyOff` seems to be the only way.

**Comment by sindresorhus** [comment]
@stroncium Can't we just document that `. listenerAdded` (or any other "meta" listener) doesn't trigger itself? I think that's the sensible behavior. Or maybe even better, "meta" listeners doesn't trigger user-facing events. ?

Alternatively, we could have `willAddListener`/`didAddListener`, but I don't really see how that's needed.

---

> Also, while we're at it, why don't we add startedHavingListeners/stoppedHavingListeners, as apart from debugging, that's what this is usually used for, disabling functionality when no one listens.

👍

**Comment by sindresorhus** [comment]
> In that case, when would listenerAdded be called for onAny? We can't just loop through all the current listeners since that simply won't work as referred to in #46 (comment).

`.listenerAdded` doesn't carry any behavior. It's just a hint on what to do. `.on()` and `.onAny()` can have different behavior for the same symbol.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/emittery/pull/43 is merged. So this can now be done.
