### ISSUE TITLE
Enhance `emit` return logic

### ISSUE THREAD

**Issue by zhaoyao91** [sindresorhus/emittery#47]
First, thx for this great package!

At first I don't know if the promise of emit resolves to the results of event handlers  after a trying with codesandbox. I thought this nice feature could be mentioned in the README.

According to the doc, promise of emit would wait for all events to be done or any to be rejected.  Could you support more options such as return on the first resolve?

**Comment by sindresorhus** [comment]
> I thought this nice feature could be mentioned in the README.

I agree. We should more clearly document that.

> Could you support more options such as return on the first resolve?

What's the use-case?

**Comment by zhaoyao91** [comment]
Previously I planed to use it to mock function calling but via event, so the caller would return fast while allowing other listeners to know what happend. Now my use cases are gone. Yes it may be somehow narrow.

**Comment by iamnapo** [comment]
I guess this is not applicable anymore cause of #55 ?

**Comment by sindresorhus** [comment]
Yup
