### ISSUE TITLE
Suggestion: support numeric event names

### ISSUE THREAD

**Issue by elderapo** [sindresorhus/emittery#54]
It would be cool if numeric "event names" were supported. They can be especially useful in typescript:

```ts
import * as emittery from 'emittery';

enum ProtocolMessage {
    Action,
    OtherAction,
}

type ProtocolMessages = {
    [ProtocolMessage.Action]: { aaa: string }
    [ProtocolMessage.OtherAction]: { bbb: 123 }
}

const ee = new emittery.Typed<ProtocolMessages>();

// Argument of type 'ProtocolMessage.Action' is not assignable to parameter of type 'never'.(2345)
ee.emit(ProtocolMessage.Action, { aaa: "messaggeee" });
```

**Comment by Richienb** [comment]
@sindresorhus Any comment?

**Comment by sindresorhus** [comment]
@Richienb You first. (Meaning, there's a reason I didn't comment yet. I'm not sure. More opinions/arguments for and against are needed)

I'm personally split about it. I guess it could be useful for TS, but that's the only use-case I can think of too. I love enums in other languages, but in TS, they're honestly an [awkward misfeature](https://medium.com/@maxheiber/alternatives-to-typescript-enums-50e4c16600b1), so not sure I want to encourage its use. Debuggability with just numbers would be bad too (even symbols have a debug description).

**Comment by Richienb** [comment]
@sindresorhus Cool. I guess in that case we should wait for people to +1 this feature enough that adding it would be a unanimous decision. *On an unrelated note, can you check this [comment](https://github.com/sindresorhus/terminal-image/pull/23#issuecomment-645223726) regarding terminal-image supporting animated gifs?*

**Comment by sindresorhus** [comment]
You still didn't share *your opinion* about it.

**Comment by Richienb** [comment]
@sindresorhus I personally don't use Typescript enums but I think it would be useful to add support so that people who do would find that it just works.

**Comment by sindresorhus** [comment]
I've decided to pass on this.
