### ISSUE TITLE
`.emit()` should not receive the returned value from `.on()`

### ISSUE THREAD

**Issue by davidmurdoch** [sindresorhus/emittery#55]
I noticed that you can return a value from an event handler, e.g.,

```javascript
event.on("myEvent", () => 123);
const value = await event.emit("myEvent");
value[0] === 123; // true
```

But the `Emittery.Typed` types don't support the return type, so typescript thinks `value` is always `void`.

Is this a feature that you'd like to be supported in the TypeScript types? If so, I can probably find some time to put a PR together. Are there any gotchas I should be aware of?

I hacked together something to make it "work" for my code base (it's not quite right), though this would result in breaking changes:

```typescript
class Typed<EventDataMap extends Events, EmptyEvents extends EventName = never> extends Emittery.Typed {
	on<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name, listener: (eventData: Parameters<EventDataMap[Name]>[0]) => void): Emittery.UnsubscribeFn;
	on<Name extends EmptyEvents>(eventName: Name, listener: () => void): Emittery.UnsubscribeFn;

	events<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name): AsyncIterableIterator<Parameters<EventDataMap[Name]>[0]>;

	once<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name): Promise<ReturnType<EventDataMap[Name]>>;
	once<Name extends EmptyEvents>(eventName: Name): Promise<ReturnType<EventDataMap[Name]>>;

	off<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name, listener: (eventData: Parameters<EventDataMap[Name]>[0]) => void): void;
	off<Name extends EmptyEvents>(eventName: Name, listener: () => void): void;

	onAny(listener: (eventName: EventNameFromDataMap<EventDataMap> | EmptyEvents, eventData?: EventDataMap[EventNameFromDataMap<EventDataMap>]) => void): Emittery.UnsubscribeFn;
	anyEvent(): AsyncIterableIterator<[EventNameFromDataMap<EventDataMap>, EventDataMap[EventNameFromDataMap<EventDataMap>]]>;

	offAny(listener: (eventName: EventNameFromDataMap<EventDataMap> | EmptyEvents, eventData?: EventDataMap[EventNameFromDataMap<EventDataMap>]) => void): void;

	emit<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name, eventData: Parameters<EventDataMap[Name]>[0]): Promise<ReturnType<EventDataMap[Name]>>;
	emit<Name extends EmptyEvents>(eventName: Name): Promise<ReturnType<EventDataMap[Name]>>;

	emitSerial<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name, eventData: Parameters<EventDataMap[Name]>[0]): Promise<ReturnType<EventDataMap[Name]>>;
	emitSerial<Name extends EmptyEvents>(eventName: Name): Promise<ReturnType<EventDataMap[Name]>>;
}
```

**Comment by sindresorhus** [comment]
I think that's an oversight in the JS code. I don't think that should be allowed. Event handlers and emitters should not be tightly coupled like that.

**Comment by davidmurdoch** [comment]
Perhaps, I was surprised it actually worked.

I was thinking it could be used as a sort of jQuery-esque event cancellation signal (like `return false` in an event handler stops propagation and prevents default).

I do kind of like it as as feature for use in an _internal_ API I've prototyped. Though it wouldnt be the end of the world for me if it were removed.

Feel free to close if it's just not something you want to officially support. Thanks!

**Comment by sindresorhus** [comment]
> I was thinking it could be used as a sort of jQuery-esque event cancellation signal (like return false in an event handler stops propagation and prevents default).

If that would to be supported, I still don't think it should be exposed to the user in this way.

> Feel free to close if it's just not something you want to officially support. Thanks!

We still need to disallow it in the JS code.
