### ISSUE TITLE
TS Error when using .events() with multiple event names parameter

### ISSUE THREAD

**Issue by mspae** [sindresorhus/emittery#58]
Example:

```typescript
import EventEmitter from 'emittery';

const EE = new EventEmitter.Typed<{
  'event-name-A': string;
  'event-name-B: string;
}>();

const iteratorSingle = EE.events('event-name-A'); // This works and has correct type info
const iteratorMultiple = EE.events(['event-name-A', 'event-name-B']); // This doesn't compile. See error below.
```

This is the typescript error:
```
Argument of type 'string[]' is not assignable to parameter of type '"event-name-A" | "event-name-B".
  Type 'string[]' is not assignable to type '"event-name-A"'.
```

I'm not such a typescript whiz but I assume the type discrimation between single and multi value `.events` isn't working correctly.

**Comment by sindresorhus** [comment]
// @LuKks

**Comment by LuKks** [comment]
I can't or I don't know how to reproduce the error, I actually don't use TypeScript.
What happen if you create the emittery instance without `Typed`? Just a normal instance:
```js
import EventEmitter from 'emittery';

const EE = new EventEmitter();

const iteratorSingle = EE.events('event-name-A');
const iteratorMultiple = EE.events(['event-name-A', 'event-name-B']);
```

I can't run the code due another error (I think is a misconfiguration on my side):
`node_modules/emittery/index.d.ts:195:33 - error TS2304: Cannot find name 'AsyncIterableIterator'.`
