### ISSUE TITLE
Emit seems synchronous

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#6]
Oh this looks really nice @sindresorhus! Having written some of these things before I had a look through the code and something stood out.

Looking at these two lines in the `emit()` function: https://github.com/sindresorhus/emittery/blob/82cda78b460fd5cd972addec73bd04eac6039a06/index.js#L41:L42

Listeners are executed synchronously, in the same tick as the call to `emit()`. If a listener throws (rather than returning a rejected promise) no subsequent listeners will be called. This seems to go against the API description:

>emit(eventName, [data])
>
>Trigger an event asynchronously, optionally with some data. Listeners are called in the order they were added, but execute concurrently.
>
>Returns a promise for when all the event listeners are done. Done meaning executed if synchronous or resolved when an async/promise-returning function. You usually wouldn't want to wait for this, but you could for example catch possible errors. If any of the listeners throw/reject, the returned promise will be rejected with the error, but the other listeners will not be affected.

If I'm reading this right then the following should fix the behavior:

```js
// Top-level
const resolved = Promise.resolve()

async emit(eventName, eventData) {
		await resolved;
		const listeners = [...this._getListeners(eventName)].map(async listener => listener(eventData));
		// and so on
}
```

Also, rather than `[...listeners].map(fn)` you could use `Array.from(listeners, fn)` which I imagine is marginally more efficient.

**Comment by sindresorhus** [comment]
Thanks for looking through the code. You're absolutely right. I missed that. Does https://github.com/sindresorhus/emittery/commit/3d73a7406204cde165600eb3ed3db93030ffbadb look good?

**Comment by sindresorhus** [comment]
> async emit(eventName, eventData) {
>		await resolved;

And when I thought I knew async functions... I was sure they always executed in the next micro-task/tick. That's a bit conceiving though. They're called async functions, but the body doesn't actually execute async...

> Also, rather than [...listeners].map(fn) you could use Array.from(listeners, fn) which I imagine is marginally more efficient.

I prefer spread. The difference is probably negligible.

**Comment by novemberborn** [comment]
Yep looks great.

> And when I thought I knew async functions... I was sure they always executed in the next micro-task/tick. That's a bit conceiving though. They're called async functions, but the body doesn't actually execute async...

Heh. Just pretend they're `() => new Promise(resolve => {
  resolve(returnValue)
})` style functions instead.

I realized you could also do `await null`, but awaiting a promise is probably clearer.
