### ISSUE TITLE
TypeScript return type for listeners is void

### ISSUE THREAD

**Issue by davesidious** [sindresorhus/emittery#62]
The Emittery code supports awaiting a promise returned from the event listener function, yet the TypeScript return type of the listener is `void`:

```typescript
    on<Name extends EventNameFromDataMap<EventDataMap>>(eventName: Name, listener: (eventData: EventDataMap[Name]) => void): Emittery.UnsubscribeFn;
    on<Name extends EmptyEvents>(eventName: Name, listener: () => void): Emittery.UnsubscribeFn;
````
Should this not at least support returning a promise, or have I misunderstood something?

**Comment by sindresorhus** [comment]
That's intentional. The emitter and subscriber should not be tightly coupled. That's the whole point of an event-driven system.

https://github.com/sindresorhus/emittery/issues/55#issuecomment-622910461

**Comment by davesidious** [comment]
Interesting - thanks.  I was under the impression we could wait for the async event listeners to resolve (obviously not caring about their return value, just that they have resolved).  Would that tightly couple them?  I'm not sure what your definition of "tightly coupled" is, but to me waiting for an asynchronous operation to complete (and never using its response) wouldn't count...
