### ISSUE TITLE
Why is Emittery.Typed a separate class?

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/emittery#67]
Curious why `Typed` needs to be a separate class? Couldn't the type signature of the main class just be

```typescript
class Emittery<EventDataMap extends Events = Events, EmptyEvents extends EventName = never> {
}
```

to get basically the same result?

**Comment by sindresorhus** [comment]
I don't remember. I tried to look through the [original PR](https://github.com/sindresorhus/emittery/pull/17), but it didn't really give any insight. I guess it was either lack of TS knowledge or some TS limitation. It would indeed be nice to merge it into the main types.
