### ISSUE TITLE
TS: Constrained generics

### ISSUE THREAD

**Issue by AuHau** [sindresorhus/emittery#71]
I guess is a more generic TS question, but I am trying to extend `Emittery.Typed` with a generic class that has already some predefined event's names using the generic's contrain like this:

```ts
import Emittery from 'emittery'

interface BasicEvents {
  hello: string
}

class GenericTest<ValueEvents extends BasicEvents, NonValueEvents extends string | symbol> extends Emittery.Typed<ValueEvents, NonValueEvents> {
  someMethod (): void {
    this.emit('hello', 'world') // This should be alright
  }
}
```

But I am getting TS error:
```
error TS2345: Argument of type '"hello"' is not assignable to parameter of type 'Extract<keyof ValueEvents, string | symbol>'.

330       this.emit('hello', e)
                    ~~~~~~~
```

Any ideas what I am missing?

[TS Playground](https://www.typescriptlang.org/play?ts=4.1.2#code/PQkAgMQJwewWzAUTgSwC5oKZQJ4Cg0cAHTMJAN0wDs0A5AQzlIF4wBnNKFKgczAB92OOACMYAGzzcsUAGb0AxqUSUabMAG8AvgWLLVdRpmjwAIvTT0AsvSIAeFdTTnLNogD4wrRAA9OitDsAa0wcGFkKJxdrWwAaSJoGJncAbjx0hXF6NnVkdBkcBwNotzBMP2oAE1yDNk8NdLIyTFRApNJyrCpqhMMmEzgS2yKoixiPdwAKTAN2gC4wdviZ0csFxxohogBtdoBdAEoFgAVYVDZMO3IYFEr6vCbHsChMNABXKCowU-gUC4A6F5sCSUSYHB5NHQ6PCgUBgADCbw48DAChglUw6UIJDAACFsigFBs0OpWA0yAALTDicQwBYcLi8PDQtFUDhlVrYLxgKiYADuSFaBTs+LYhOJdTBeBa6Gw-xlaEmAHIqTSYEr4kq+TAoOJKkqDmBwAAVCl-MDm+jiLg8CloaWcqDy1rKqgwKgAWlVtI1YC1Or1BqNwAROpeCjQ4hwYCIhJClTAbyIYGyPPdYHIVtu6TwmWy6gA4tRsITjZgOHYAGpWt6YCVlCrddSi8W1eK0d3V8S1+udKrqBncPiCNjCMTiTx9puC-LYQpdnu1e5kYFMKyvCnosBghbXW6aCFkNBmtjO9DK73qzXa3X6w0mk-sTdvPVgESkK02u0QqF4IA)

**Comment by sindresorhus** [comment]
// @mmkal In case you have time to answer this. If not, feel free to disregard.

**Comment by mmkal** [comment]
I agree the compiler should be smart enough to figure out this is ok, so maybe worth making a TypeScript issue? In the meantime, you can easily workaround by explicitly including the base type in emittery's generic, i.e. `extends Emittery.Typed<ValueEvents & BasicEvents, NonValueEvents>`:

```diff
import Emittery from 'emittery'

interface BasicEvents {
  hello: string
}

class GenericTest<ValueEvents extends BasicEvents, NonValueEvents extends string | symbol>
-  extends Emittery.Typed<ValueEvents, NonValueEvents> {
+  extends Emittery.Typed<ValueEvents & BasicEvents, NonValueEvents> {
  someMethod (): void {
    this.emit('hello', 'world') // This is alright
  }
}
```

[Playground link](https://www.typescriptlang.org/play?ts=4.1.2#code/PQkAgMQJwewWzAUTgSwC5oKZQJ4Cg0cAHTMJAN0wDs0A5AQzlIF4wBnNKFKgczAB92OOACMYAGzzcsUAGb0AxqUSUabMAG8AvgWLLVdRpmjwAIvTT0AsvSIAeFdTTnLNogD4wrRAA9OitDsAa0wcGFkKJxdrWwAaSJoGJncAbjx0hXF6NnVkdBkcBwNotzBMP2oAE1yDNk8NdLIyTFRApNJyrCpqhMMmEzgS2yKoixiPdwAKTAN2gC4wdviZ0csFxxohogBtdoBdAEoFgAVYVDZMO3IYFEr6vCbHsChMNABXKCowU-gUC4A6F5sCSUSYHB5NHQ6PCgUBgADCbw48DAChglUw6UIJDAACFsigFBs0OpWA0yAALTDicQwBYcLi8PDQtFUDhlVrYLxgKiYADuSFaBTs+LYhOJdTBeBa6Gw-xlaEmAHIqTSYEr4kq+TAoOJKkqDmBwAAVCl-MDm+jiLg8CloaWcqDy1rKqgwKgAWlVtI1YC1Or1BqNwAROpeCjQ4hwYCIhJClTAbyIYGyPPdYHIVtu6TwmWy6gA4tRsITjZgOHYAGpWt6YCVlCrddSi8W1eK0d3V8S1+udKrqBncPiCNjCMTiTx9puC-LYQpdnu1MAAMjxBKJtXuZGBTCsrwp6LAYIW11umghZDQZrYzvQyu96s12t1+sNJuv7APbz1YBEpCtNp2hCULpBieYvKi7rsnAOqYAAyiQCgoLI4pCtgCxFryXAKGWFYaA+9KcEOKRgDwMDoiIOCYAsVBvKIXJaJqsjkUq7jpDBLwIZgSEoUSaFOgq97Uj6T4Bq+wZgDAQR4Bx8GIchqGzgJLpKmRFFUb6ACMABMADMb4hgAguIwKSdJslcTxikYHKglKm6noPr6-ovkG4DwmG3GRtGsYKPGibJqmDkZlmlR4EAA)

**Comment by AuHau** [comment]
Oh! That is interesting! Thanks a lot for pointers! 

Closing this as it is not really Emittery's problem...
