### ISSUE TITLE
Release notes for 0.8.0 are slightly wrong

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/emittery#75]
Minor thing - the release notes for https://github.com/sindresorhus/emittery/releases/v0.8.0 are not quite right. Right now it's:

```diff
-const emitter = new Emittery.Typed<{value: string}, 'open' | 'close'>();
+const emitter = new Emittery<
+	{
+		open: string,
+		close: undefined
+	}
+>();
```

When it should be:

```diff
-const emitter = new Emittery.Typed<{value: string}, 'open' | 'close'>();
+const emitter = new Emittery<
+	{
+		value: string,
+		open: undefined,
+		close: undefined
+	}
+>();
```

<details>
<summary>(just for fun, here's an extremely unhelpful diff-diff which I don't think GitHub knows how to render):</summary>

```diff
-const emitter = new Emittery.Typed<{value: string}, open | close>();
+const emitter = new Emittery<
+{
[-+open:-]{++value:+} string,
{++open: undefined,+}
+close: undefined
+}
+>();
```

</details>

**Comment by sindresorhus** [comment]
I was just following the readme diff, so then the readme is incorrect too: https://github.com/sindresorhus/emittery/commit/df35ea6f74907348e33b974bc3645641afe28d94#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15L325-R332

// @airhorns

**Comment by mmkal** [comment]
The readme looks fine, it's just using a different example than it was before. In the release notes there's an implication that the old code and new code would do the same thing. The release is read automatically by tools like renovate, so it makes the upgrade instructions a bit confusing, e.g. https://github.com/sequelize/umzug/pull/428

**Comment by sindresorhus** [comment]
Ah, I missed that. Release notes fixed.
