### ISSUE TITLE
Breaking change in 0.8.1

### ISSUE THREAD

**Issue by linonetwo** [sindresorhus/emittery#76]
I used to do this in 0.8.0:

```js
    this.on('app-data:update-state', this.updateAppState);
    this.on('tray:get-options', this.renderTrayOptions);
```

in a class extends Emittery

but now it will throw.

**Comment by sindresorhus** [comment]
// @airhorns @papb

**Comment by linonetwo** [comment]
Sorry， not throw, but the typescript will say I can't use these event names...

**Comment by papb** [comment]
Hi! Can you provide a complete minimal example?

**Comment by airhorns** [comment]
We made a breaking change that was intentional and follows the SemVer spec that allows breaking changes in minor versions pre 1.0. See https://github.com/sindresorhus/emittery/releases/tag/v0.8.0 for information on how to upgrade.

**Comment by papb** [comment]
@airhorns I think you're mistaken, OP's code broke when upgrading from 0.8.0 to 0.8.1

**Comment by airhorns** [comment]
Ah my mistake!

**Comment by linonetwo** [comment]
I know, I was using 

```ts
abstract class BaseManager
  extends  Emittery<IDataEventMap, keyof IEmptyEventMap>
````

And now it should be just

```ts
abstract class BaseManager
  extends  Emittery.Typed<IDataEventMap>
````

Thanks for point out, but this should actually be 0.9.0 ... hah
