### ISSUE TITLE
TypeScript: 0.8.1 breaks re-exported `on`

### ISSUE THREAD

**Issue by SimenB** [sindresorhus/emittery#78]
```ts
import Emittery = require('emittery');

type Events = {
  foobar: string;
}

export class MyThing {
  private readonly eventEmitter = new Emittery<Events>();

  on = this.eventEmitter.on.bind(this.eventEmitter);
}
```

Using 0.8.0 this works fine, but upgrading to 0.8.1 gives

```
src/index.ts:10:3 - error TS2527: The inferred type of 'on' references an inaccessible 'unique symbol' type. A type annotation is necessary.

10   on = this.eventEmitter.on.bind(this.eventEmitter);
     ~~

src/index.ts:10:3 - error TS4029: Public property 'on' of exported class has or is using name 'listenerAdded' from external module "/Users/simen/repos/emittery-stuff/node_modules/emittery/index" but cannot be named.

10   on = this.eventEmitter.on.bind(this.eventEmitter);
     ~~

src/index.ts:10:3 - error TS4029: Public property 'on' of exported class has or is using name 'listenerRemoved' from external module "/Users/simen/repos/emittery-stuff/node_modules/emittery/index" but cannot be named.

10   on = this.eventEmitter.on.bind(this.eventEmitter);
     ~~


Found 3 errors.
```

Comes from #73.

I've put together a small repo showing this: https://github.com/SimenB/emittery-type-error.

Note that this only happens if you produce `declaration` files from source

**Comment by sindresorhus** [comment]
// @airhorns @papb

**Comment by airhorns** [comment]
@SimenB would you expect your re-exported listener to be able to listen to the internal events of the event emitter?

**Comment by SimenB** [comment]
Not really, that's more of an implementation detail. So for my use case that's not needed 🙂

**Comment by airhorns** [comment]
Ok, in that case I think you should just add an explicit type annotation like the TS compiler suggests! My bad for accidentally causing this breaking change, but I think in this case the compiler is right, and this just surfaced an error that was hidden by the incorrect bits in `index.d.ts`.

**Comment by airhorns** [comment]
If @sindresorhus we could yank 0.8.1 and republish as 0.9, but I think this rebinding use case is pretty niche and 0.8.1 has been out for long enough that would cause a lot of chagrin on all the other adopters

**Comment by sindresorhus** [comment]
I don't see the point of yanking the current version. Maybe we should improve the docs though.

**Comment by beckend** [comment]
This is still a issue, where one wish to make a library that uses this one.
Simply export will fix this:
```typescript
declare const listenerAdded: unique symbol;
declare const listenerRemoved: unique symbol;

export {
  listenerAdded,
  listenerRemoved
}
```
It's for the ability to generate declarations.

**Comment by airhorns** [comment]
@beckend want to make a PR?

**Comment by beckend** [comment]
@airhorns did the minimal touch
