### ISSUE TITLE
Simple clarification

### ISSUE THREAD

**Issue by vltr** [sindresorhus/emittery#8]
Hi! Just for a simple clarification, is this project for NodeJS only? If so, just a tip, add it to your README :wink: 

Keep up the good work! My best regards! :+1:

**Comment by bfred-it** [comment]
Most of his projects are, the `npm install X` and `index.js` file should be indication enough.

**Comment by novemberborn** [comment]
This does seem reasonably clear to me, yes. Thanks for raising it though @vltr!

**Comment by vltr** [comment]
@bfred-it thanks, but I'm not familiar with the author's repositories so I thought I could just ask, imho it doesn't hurt to do so.

@novemberborn thanks for your comprehension and your time :wink:

**Comment by bfred-it** [comment]
@vltr Sure, the downvote was for the request to specify that it's a node module in the readme.
