### ISSUE TITLE
v0.9.0 throws a reference error on browser bundles

### ISSUE THREAD

**Issue by alexiglesias93** [sindresorhus/emittery#85]
I'm using **emittery** on a frontend codebase and **esbuild** for compiling and bundling, and after updating to `v0.9.0` the following error started popping up in the console:
```
Uncaught ReferenceError: process is not defined
at Function.get isDebugEnabled [as isDebugEnabled]
```

The error is originated [here](https://github.com/sindresorhus/emittery/blob/02b18ef0fdac61ddc79cdc7c4f3d2357e0908a57/index.js#L194), as the `process` variable is not available on the browser.

**Comment by alexiglesias93** [comment]
@sindresorhus I'm afraid 30a859abfdab0d6f6e37aa2967d4df307b844a92 didn't fix the issue (at least not in my case).
Still throwing an `Uncaught ReferenceError: process is not defined` exception.

I've been able to fix the issue by adding an extra check:
```javascript
static get isDebugEnabled() {
    if (!(typeof process === 'object')) return isGlobalDebugEnabled;
    
    const {env} = process || {env: {}};
    return env.DEBUG === 'emittery' || env.DEBUG === '*' || isGlobalDebugEnabled;
}
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/emittery/releases/tag/v0.9.2
