### ISSUE TITLE
Arbitrary listener return type (Typescript)

### ISSUE THREAD

**Issue by j4k0xb** [sindresorhus/emittery#88]
Right now, the listener can only return `void` or `Promise<void>`, but it shouldn't matter since the returned value is unused.
This applies especially to arrow functions:
```ts
client.on('disconnect', () => test());
function test() {
  // ...
  return 1;
}
````
> Type 'number' is not assignable to type 'void | Promise<void>'

Maybe use `() => unknown` or any for the listener instead as it works with void and all other return types

**Comment by sindresorhus** [comment]
The existing types are correct and will not be changed. They are preventing you from writing less readable code.
