### ISSUE TITLE
Legacy Node.js support

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/emittery#9]
I'd be interested in using this for projects that still need to target Node.js 4 and 5 (*cough* transitive AVA dependencies *cough*).

One idea might be to transpile `index.js` into a `legacy.js` file when publishing (and installing from GitHub). We could muck about with the tests too so we can test that file without too much effort.

This way modern codebases can simply require `emittery`, but others can require `emittery/legacy` for compatibility. And `index.js` stays nice and simple, with native `async/await`.

@sindresorhus would you be open to this?

**Comment by sindresorhus** [comment]
Sure, if someone does the work.
