### ISSUE TITLE
Enabling debug can cause circular reference error

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/emittery#95]
Repro:

```ts
import Emittery from 'emittery'

Emittery.isDebugEnabled = true

const emitter = new Emittery<{foo: any}>()

emitter.on('foo', ev => console.log({ev}))

const x = {} as any
x.x = x

emitter.emit('foo', x)
```

Error:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'x' closes the circle
```

Playground of the above: https://codesandbox.io/s/typescript-playground-export-forked-i5qzj6?file=/index.ts

Surfaced as a bug in umzug: https://github.com/sequelize/umzug/issues/541#issuecomment-1083125643

**Comment by jeffwillden** [comment]
Thanks for posting this. I'm also seeing this error. I don't know of a way to set DEBUG=* --except emittery to prevent emittery from JSONifying that reference. Do you know of a workaround aside from trying to list all the things I might want to get debug output for?

**Comment by mmkal** [comment]
@jeffwillden https://github.com/sindresorhus/emittery/blob/f3da6aba6d499db3d042c39eed3f206e8e6808a1/index.js#L219 is the offending line of code. It might make sense to just wrap that in a try/catch and set

```js
eventData = `Object with keys ${Object.keys(eventData).join(',')} failed to stringify.`
```

in the catch block? @sindresorhus thoughts?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/emittery/releases/tag/v0.10.2
