### ISSUE TITLE
No way to unsubscribe from `once`

### ISSUE THREAD

**Issue by futpib** [sindresorhus/emittery#99]
`once` returns a promise and nothing else, so if you do a `once` and it never gets emitted it's leaked forever.

**Comment by sindresorhus** [comment]
Any suggestions on how we could solve this?

One idea is to add a special symbol to the returned promise and add a `.offOnce()` method to Emittery that checks for the special symbol and unsubscribes.

**Comment by futpib** [comment]
Maybe extend the returned promise with an `unsubscribe` or `off` method?

**Comment by sindresorhus** [comment]
Yeah, that may be more discoverable.
